<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\the-third-alien.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ThirdAlien.Core/ThirdAlien.Core.csproj" />
    <ProjectReference Include="../ThirdAlien.Infrastructure/ThirdAlien.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="FluentIcons.Wpf" />
  </ItemGroup>
</Project>
